name: chrome_ext
description: chrome_ext
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  chrome_extension: ^0.3.1
  connectivity_plus: 6.0.3
  device_info_plus: 10.1.0
  dio: 5.4.3+1
  extended_image: 8.2.1

  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  get_it: 7.7.0
  http_proxy: ^1.2.2
  json_annotation: 4.9.0
  retrofit: 4.1.0
  shared_preferences: ^2.3.1
  signals: ^5.3.0
  styled_text: ^8.1.0
  system_proxy: ^0.1.0
  system_theme: ^3.0.0
  talker_flutter: ^4.4.0
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: 2.4.10
  custom_lint: ^0.5.11
  flutter_flavorizr: 2.2.3
  flutter_test:
    sdk: flutter
  json_serializable: 6.8.0
  lint: 2.3.0
  retrofit_generator: 8.1.0
  signals_lint: ^5.0.0

flutter:
  uses-material-design: true

scripts: derry.yaml
